title: "Vivek Anchewar"
logo: "/assets/logo.png"
description: "Data Analyst | SQL | Power BI | Python | Tableau"
show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme


